name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish Windows and Linux
        run: dotnet msbuild build-release.proj
      - uses: actions/upload-artifact@v4
        with:
          name: WindowSnapper-releases
          path: |
            publish/WindowSnapper-win-x64.zip
            publish/WindowSnapper-linux-x64.zip
